export const PC_LOCATIONS = ["NK", "GANESH P.C.", "PASIFIC P.C.", "ANY OTHER"];
export const BOM_ITEMS = [
  "BODY SIZE", "DOOR", "COVER", "GLAN PLATE", "MOUNTING PLATE", "C-CHANNEL",
  "L-PATTA", "GHODI", "J-CHANNEL", "BASBAR COVER", "BASBAR ANGLE", "CAPACITOR PATTA",
  "BRAKER C CHANNEL", "CANOPY", "BASE", "STAND"
];
